// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybsfsmeowisaujfuurva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlic2ZzbWVvd2lzYXVqZnV1cnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODIzMzksImV4cCI6MjA3MDE1ODMzOX0.ktOUY0JUVEiCGTl_tHfxDpMmvVVmrTPvfBUl1ul3V-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});